// kobakazu0429/src/components/Modal.tsx
import React, { FC, useContext } from "react";
import styled from "styled-components";
import { zIndex } from "@/constants/zIndex";
import { ModalContext } from "@/utils/customHooks/useModal";

export const Modal: FC = ({ children }) => {
  const { isShowingModal, closeModal } = useContext(ModalContext);

  return isShowingModal ? (
    <>
      <Wrapper>{children}</Wrapper>
      <BackGround isShowing={isShowingModal} onClick={closeModal} />
    </>
  ) : null;
};

const Wrapper = styled.div`
  width: calc(100% - 50px);
  height: calc(100% - 50px);
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: white;
  transition: opacity ease 500ms;
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  z-index: ${zIndex.modal};
`;

const BackGround = styled.div<{ isShowing: boolean }>`
  width: 100vw;
  height: 100vh;
  position: absolute;
  top: 0;
  left: 0;
  background-color: black;
  opacity: ${({ isShowing }) => (isShowing ? 0.4 : 0)};
  transition: opacity ease 500ms;
`;

// Helicoir/src/components/independents/Modal/index.vue
<template>
  <transition>
    <div class="modal__mask" v-if="show" @click="close()">
      <div class="modal__window">
        <slot name="content" />
        <div class="modal__textarea">
          <slot name="text" />
        </div>
        <div class="modal__window__buttons">
          <Button @event="enter()" v-if="confirm">{{ enterText }}</Button>
          <Button @event="close()">戻る</Button>
        </div>
      </div>
    </div>
  </transition>
</template>

<script>
import { createComponent } from '@vue/composition-api'
import Button from '~/components/atoms/Button'

export default createComponent({
  props: {
    show: {
      type: Boolean,
      default: false
    },
    confirm: {
      type: Boolean,
      default: false
    },
    enterText: String
  },
  setup(props, context) {
    const enter = () => {
      context.emit('enter')
    }
    const close = () => {
      context.emit('close')
    }
    return {
      enter,
      close
    }
  },
  components: {
    Button
  }
})
</script>

<style lang="scss" scoped>
.modal {
  &__mask {
    position: fixed;
    z-index: 102;
    top: 0;
    left: 0;
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100vw;
    height: 100vh;
    background: $__mask;
  }
  &__window {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-around;
    max-width: 80%;
    padding: 60px 100px;
    background: $__mainColor;
    &__buttons {
      display: flex;
      justify-content: space-around;
    }
  }
  &__textarea{
    width: 100%;
    margin: 0 0 20px;
    color: white;
  }
}
</style>
